version: '3'

services:
  invoiceservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8085:8085
    container_name: invoice-service
    depends_on:
      invoicedb:
        condition: service_healthy
    environment:
      - 'DB_HOST=invoicedb:3307'
  invoicedb:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: invoices
      MYSQL_TCP_PORT: 3307
    container_name: invoice-service-db
    ports:
      - 3307:3307
    expose:
      - 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10